---
log_level: INFO # Nivel de log: CRITICAL, ERROR, WARNING, INFO, DEBUG
scrapy_time_update: 500 # Tiempo (minimo 300) entre cada búsqueda (en segundos)
telegram_chatuserID: -1001678699889 # ID del chat telegram - Example: -1001647968011

flat_details:
  max_price: 0 # Precio maximo de filtro (0 = sin limite)

idealista_data:
  db_name: idealista
  urls:
    - https://www.idealista.com/venta-viviendas/madrid/hortaleza/


pisoscom_data:
  db_name: pisoscom
  urls:
    - https://www.pisos.com/venta/pisos-fuencarral_el_pardo/

fotocasa_data:
  db_name: fotocasa
  urls: 
    - https://www.fotocasa.es/es/comprar/viviendas/madrid-capital/hortaleza/l?sortType=publicationDate&latitude=40.46881501855609&longitude=-3.641945499708502&combinedLocationIds=724,14,28,173,0,28079,0,678,0
    #- shorturl.at/gxJT7
    #- https://www.fotocasa.es/es/comprar/viviendas/madrid-capital/hortaleza/l?sortType=publicationDate&latitude=40.46881501855609&longitude=-3.641945499708502&maxPrice=1100000&minRooms=2&combinedLocationIds=724,14,28,173,0,28079,0,678,0

habitaclia_data:
  db_name: habitaclia
  urls:
    - https://www.habitaclia.com/viviendas-distrito_fuencarral_el_pardo-madrid.htm

